.\"	$OpenBSD$
.\"
.\"Copyright (c) 2008-2017 Gilles Chehade <gilles@poolp.org>
.\"Copyright (c) 2017 Aaron Poffenberger <akp@hypernote.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: Nov 21 2017 $
.Dt SPFWALK 1
.Os
.Sh NAME
.Nm spfwalk
.Nd recursively look up SPF records
.Sh SYNOPSIS
.Nm spfwalk
.Bk -words
.Op Fl 46h
.Op Fl 4
.Op Fl 6
.Op Fl h
.Ar domain ...
.Ek
.Sh DESCRIPTION
.Nm
recursively looks up SPF records for the domains passed in on the command
line or stdin, printing the results to stdout, one line per record.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 4
Look-up IPv4 records.
(Disables default-lookup of IPv6 unless -6 specified.)
.It Fl 6
Look-up IPv6 records.
(Disables default-lookup of IPv4 unless -4 specified.)
.It Fl h
Help message.
.El
.Sh EXAMPLES
Look-up a single domain:
.Bd -literal
	spfwalk example.com
.Ed
.Pp
Look-up IPv4 records of multiple domains:
.Bd -literal
	spfwalk -4 example.com example.org
.Ed
.Sh DIAGNOSTICS
.Nm
utility always exits 0.
.Sh BUGS
.Nm
should return error codes for conditions like failed look-ups.
